import { Schema, model, type InferSchemaType, type HydratedDocument, Types } from 'mongoose';

/**
 * Someone in the audience.
 *
 * Anonymity is a promise, not a setting we quietly ignore. When a session is
 * anonymous we store no IP address, no user agent and no fingerprint — only
 * a random token the phone generated for itself. That token is meaningless
 * outside this session and cannot be traced back to a person.
 */
const participantSchema = new Schema(
  {
    sessionId: { type: Types.ObjectId, ref: 'Session', required: true, index: true },

    /**
     * Random value generated by the participant's browser and kept in local
     * storage. Lets someone refresh the page without becoming a new person,
     * and lets the server enforce one-answer-per-device.
     */
    deviceToken: { type: String, required: true, maxlength: 64 },

    /** Only present when the deck asks for names. */
    displayName: { type: String, default: '', trim: true, maxlength: 60 },

    /** Set only when the session requires people to be logged in. */
    userId: { type: Types.ObjectId, ref: 'User', default: null },

    /** BCP-47 tag chosen by the participant, used for translation. */
    locale: { type: String, default: 'en', maxlength: 16 },

    /** Running quiz total, updated as answers arrive. */
    score: { type: Number, default: 0 },

    firstSeenAt: { type: Date, default: Date.now },
    lastSeenAt: { type: Date, default: Date.now },

    /** Presenter can remove a disruptive participant. */
    blockedAt: { type: Date, default: null },
  },
  { timestamps: false },
);

/** One participant row per device per session. */
participantSchema.index({ sessionId: 1, deviceToken: 1 }, { unique: true });
/** Leaderboard query. */
participantSchema.index({ sessionId: 1, score: -1 });

export type ParticipantDoc = HydratedDocument<InferSchemaType<typeof participantSchema>>;

export const Participant = model('Participant', participantSchema);
